# Created by Marcin Jarczewski on 29/11/2023.
FROM ubuntu:22.04
COPY ./client.c ./client.c
COPY Makefile.docker Makefile
RUN apt-get update
RUN apt-get install -y netcat make gcc
RUN make client
CMD ["sleep", "infinity"]
